name: rel

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22
        id: go

      - name: Check out code into go module directory
        uses: actions/checkout@v2

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Tidy
        run: go mod tidy

      - name: Install pkger
        run: go install github.com/markbates/pkger

      - name: Run pkger
        run: ./pkgtemplates.sh

      - name: Build darwin-amd64
        run: GOOS=darwin GOARCH=amd64 go build -v -o jiffy

      - name: Gzip darwin-amd64
        run: tar cvzf jiffy-darwin-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build freebsd-amd64
        run: GOOS=freebsd GOARCH=amd64 go build -v -o jiffy

      - name: Gzip freebsd-amd64
        run: tar cvzf jiffy-freebsd-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build freebsd-arm
        run: GOOS=freebsd GOARCH=arm go build -v -o jiffy

      - name: Gzip freebsd-arm
        run: tar cvzf jiffy-freebsd-arm.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build openbsd-amd64
        run: GOOS=openbsd GOARCH=amd64 go build -v -o jiffy

      - name: Gzip openbsd-amd64
        run: tar cvzf jiffy-openbsd-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build openbsd-arm
        run: GOOS=openbsd GOARCH=arm go build -v -o jiffy

      - name: Gzip openbsd-arm
        run: tar cvzf jiffy-openbsd-arm.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build linux-amd64
        run: GOOS=linux GOARCH=amd64 go build -v -o jiffy

      - name: Gzip linux-amd64
        run: tar cvzf jiffy-linux-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build linux-arm
        run: GOOS=linux GOARCH=arm go build -v -o jiffy

      - name: Gzip linux-arm
        run: tar cvzf jiffy-linux-arm.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build linux-arm64
        run: GOOS=linux GOARCH=arm64 go build -v -o jiffy

      - name: Gzip linux-arm64
        run: tar cvzf jiffy-linux-arm64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build linux-mips64
        run: GOOS=linux GOARCH=mips64 go build -v -o jiffy

      - name: Gzip linux-mips64
        run: tar cvzf jiffy-linux-mips64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build linux-ppc64
        run: GOOS=linux GOARCH=ppc64 go build -v -o jiffy

      - name: Gzip linux-ppc64
        run: tar cvzf jiffy-linux-ppc64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      - name: Build linux-s390x
        run: GOOS=linux GOARCH=s390x go build -v -o jiffy

      - name: Gzip linux-s390x
        run: tar cvzf jiffy-linux-s390x.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz jiffy README.md

      #- name: Generate Changelog
      #run: echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            jiffy-darwin-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-freebsd-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-freebsd-arm.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-openbsd-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-openbsd-arm.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-linux-amd64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-linux-arm.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-linux-arm64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-linux-mips64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-linux-ppc64.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
            jiffy-linux-s390x.${{ steps.get_tag_name.outputs.VERSION }}.tar.gz
          #body_path: ${{ github.workflow }}-CHANGELOG.txt
          body_path: CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
